AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RecallAI FastAPI Backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: python3.10
    Architectures:
      - x86_64

Resources:

  # -------------------------------------------
  # Main Lambda Function
  # -------------------------------------------
  RecallAIBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: recallai.main.handler                # <--- FIXED
      CodeUri: .          # <--- Your code
      FunctionName: recallai-backend       # <--- FIXED (no underscore)
      Events:
        ApiGatewayProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          OPENAI_API_KEY: !Ref OpenAIApiKey
          OPENAI_EMBEDDING_MODEL: !Ref OpenAIEmbeddingModel

Outputs:
  ApiUrl:
    Description: Invoke URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
