AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RecallAI FastAPI Backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: python3.10
    Architectures:
      - x86_64

Resources:
  RecallAIBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: ./
      FunctionName: recall-ai-backend
      Events:
        ApiGatewayProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: Invoke URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
